name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 and configure Maven for GitHub Packages
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish to GitHub Packages
        run: mvn -B deploy -Drevision=${GITHUB_REF_NAME#v}

      - name: Upload JAR to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/javaxtend-${GITHUB_REF_NAME#v}.jar
          asset_name: javaxtend-${GITHUB_REF_NAME#v}.jar
          tag: ${{ github.ref_name }}
          overwrite: true
